#!/usr/bin/env bash

function isShellScript() {
  if file --mime-type $1 | grep -q text/x-shellscript$; then
    echo "[INFO] File is a shell script."
  else
    echo "[ERROR] File isn't a shell script"
    exit 1
  fi
}

function isNotEmpty() {
  if [ -s $1 ]; then
    echo "[INFO] $1 isn't empty"
  else
    echo "[ERROR] $1 is empty"
  fi
}

read -p "Filename: " filename

path="$(pwd)/$filename"

function main() {
  isShellScript $1
  isNotEmpty $1
  echo "[INFO] Adding Symlink of the script to /etc/rc6.d/"
  sudo ln -s $1 /etc/rc6.d/K99$filename
  echo "[INFO] Added symlink of the script."
  ls -alF /etc/rc6.d/K99$filename
}

main $path
